[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'hodaun'
version = '0.1.0'

[dependencies]
cpal.optional = true
cpal.version = '0.13.5'
crossbeam-channel = '0.5.4'
rand.features = ['small_rng']
rand.version = '0.8.5'
rustfft.optional = true
rustfft.version = '6'
thiserror.optional = true
thiserror.version = '1'

[features]
analyze = ['rustfft']
default = ['analyze', 'input', 'output']
input = ['cpal', 'thiserror']
output = ['cpal', 'thiserror']
