[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'hodaun'
version = '0.1.0'

[dependencies]
cpal.optional = true
cpal.version = '0.14.2'
hound.optional = true
hound.version = '3.5.0'
rand.features = ['small_rng']
rand.version = '0.8.5'
thiserror.optional = true
thiserror.version = '1'

[features]
default = ['input', 'output', 'wav']
input = ['cpal', 'thiserror']
output = ['cpal', 'thiserror']
wav = ["hound"]
