[package]
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'
name = 'hodaun'
version = '0.1.0'

[dependencies]
cpal = '0.13.5'
crossbeam-channel = '0.5.4'
rand.features = ['small_rng']
rand.version = '0.8.5'
